// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5WkG0IA4F8aTyAgLIYrAHQhladN8sUtY',
    appId: '1:915843536549:web:05971ad90edd96aa3b1f4c',
    messagingSenderId: '915843536549',
    projectId: 'storelytics-644ae',
    authDomain: 'storelytics-644ae.firebaseapp.com',
    storageBucket: 'storelytics-644ae.firebasestorage.app',
    measurementId: 'G-PEZR254Y7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAANWdKHyv9nkumTq6RDHzdVsA_wtc-2nY',
    appId: '1:915843536549:android:61b22c7393a71b9d3b1f4c',
    messagingSenderId: '915843536549',
    projectId: 'storelytics-644ae',
    storageBucket: 'storelytics-644ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOQ2Xr7BEpdOihHziiSUTiDxtHJ6nJkew',
    appId: '1:915843536549:ios:53c687cbdf1afc913b1f4c',
    messagingSenderId: '915843536549',
    projectId: 'storelytics-644ae',
    storageBucket: 'storelytics-644ae.firebasestorage.app',
    iosBundleId: 'com.storelytics.storelytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOQ2Xr7BEpdOihHziiSUTiDxtHJ6nJkew',
    appId: '1:915843536549:ios:f94fd7e7e1275e703b1f4c',
    messagingSenderId: '915843536549',
    projectId: 'storelytics-644ae',
    storageBucket: 'storelytics-644ae.firebasestorage.app',
    iosBundleId: 'yes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5WkG0IA4F8aTyAgLIYrAHQhladN8sUtY',
    appId: '1:915843536549:web:8d7d2c98beb2265c3b1f4c',
    messagingSenderId: '915843536549',
    projectId: 'storelytics-644ae',
    authDomain: 'storelytics-644ae.firebaseapp.com',
    storageBucket: 'storelytics-644ae.firebasestorage.app',
    measurementId: 'G-W8MCJG7TJQ',
  );
}
